### ISSUE TITLE
C++ wrapper

### ISSUE THREAD

**Issue by Flamefire** [erikd/libsamplerate#71]
I was considering to write a C++ wrapper for the C classes for our project to slightly ease the use.

Is there some interest to have this in the upstream project as e.g. libsamplerate.hpp with some tests? @erikd 

It would be:

- wrapper around `SRC_STATE` with copy/move operators (C++11 required)
- overloads for `src_short_to_float_array` and friends as `to_float_array` and `from_float_array`

**Comment by erikd** [comment]
Why overloads for `src_short_to_float_array` ?

**Comment by Flamefire** [comment]
Have 1 function each for converting from/to float to allow for more generic user code:

```
std::vector<short> doConvert(std::vector<short> data){
  std::vector<float> floats(data.size());
  to_float_array(data.data(), data.size(), floats.data());
  // Work with floats
  from_float_array(floats.data(), floats.size(), data.data());
  return data;
}
```

The overloads allow to change the type of parameter data to e.g. `std::vector<int>` without touching the rest of the code.

This gets more powerful the more conversion functions exist (see e.g. #72)

**Comment by erikd** [comment]
You have not even read (or maybe misunderstood) the [documentation](http://www.mega-nerd.com/libsamplerate/api_misc.html#Aux) for those auxiliary functions. I actually regret having ever added them to this library, because having them encourages suggestions like this one.

This library does sample rate conversion. It should not do anything else.

> This gets more powerful the more conversion functions exist (see e.g. #72)

Audio data stored 8 bit has a dynamic range of 42db which is about nowhere near adequate fidelity for professional audio purposes and significantly less that even extremely primitive audio compression algorithms like u-law and A-law. As far as I am concerned providing conversion functions to convert to and from that format is waste of time unless it is to provide the ability to read legacy file formats (for which you would use libsndfile).

**Comment by Flamefire** [comment]
> You have not even read (or maybe misunderstood) the documentation for those auxiliary functions. 

Then I'm missing your point. What exactly do you mean? The linked docu states `There are <n> auxillary functions for converting arrays of float data to and from <other types> data. [...] [values are] automatically scaled [...] values which would overflow [...] are clipped.` (shortened to be slightly more general and show how I read it)

> This library does sample rate conversion. It should not do anything else.

Ok sure, understand this. Then cut those overloads from this issue. The C++ wrapper would still be a nice addition to have RAII provided by the library.

> to read legacy file formats (for which you would use libsndfile).

Just a note: That legacy format is not readable by libsndfile. We still need the conversion to float without round-tripping via a WAV file (create WAV header, write to file, load with libsndfile, convert, optionally store) Having the conversions of raw data in a library would avoid having to reimplement (and test) it in user code and this looked like the place to do that (see above note about how I understood the docu).

**Comment by erikd** [comment]
The scaling mentioned in that documentation is correct for `short` but unlikely to be correct for any type which is not `short`.

As for your legacy format, it makes *far* more sense to add support for it to libsdnfile than it does adding the conversion functions here.
